import Check from './Check';
import Close from './Close';
import Folder from './Folder';
import Home from './Home';
import Menu from './Menu';
import Minus from './Minus';
import Spinner from './Spinner';
import Ticket from './Ticket';
import User from './User';
import Users from './Users';
import Search from './Search';
import ChevronDown from './ChevronDown';
import ChevronUp from './ChevronUp';
import ErrorTriangle from './ErrorTriangle';
import Email from './Email';
import Phone from './Phone';
export { Check, Close, Folder, Home, Menu, Minus, Spinner, Ticket, User, Users, Search, ChevronDown, ChevronUp, ErrorTriangle, Email, Phone };
