import Check from './Check';
import Close from './Close';
import Folder from './Folder';
import Home from './Home';
import Menu from './Menu';
import Minus from './Minus';
import Spinner from './Spinner';
import Ticket from './Ticket';
import User from './User';
import Users from './Users';
import Search from './Search';
export { Check, Close, Folder, Home, Menu, Minus, Spinner, Ticket, User, Users, Search };
